export interface Program {
    start: string;
    end: string;
    name: string;
    subtitle?: string;
}

const scheduleMonday: Program[] = [
    { start: '00:00', end: '00:10', name: 'REPÓRTER520', subtitle: 'As notícias que movimentam o seu dia.' },
    { start: '00:10', end: '02:00', name: 'LOVE HITS', subtitle: 'As melhores canções de amor, de todos os tempos.' },
    { start: '02:00', end: '05:50', name: 'INSÔNIA', subtitle: 'A trilha sonora perfeita para a sua madrugada.' },
    { start: '05:50', end: '06:00', name: 'RÁDIO520 VIVA MELHOR', subtitle: 'Dicas de saúde e bem-estar para uma vida mais leve.' },
    { start: '06:00', end: '07:50', name: 'GIRO520', subtitle: 'Comece o dia bem informado e com muita música.' },
    { start: '07:50', end: '08:00', name: 'MÚSICA DO DIA', subtitle: 'O hit que não sai da sua cabeça, em destaque.' },
    { start: '08:00', end: '10:00', name: 'CAFEÍNA', subtitle: 'A dose extra de energia e música para as suas manhãs.' },
    { start: '10:00', end: '10:10', name: 'REPÓRTER520', subtitle: 'As notícias que movimentam o seu dia.' },
    { start: '10:10', end: '13:00', name: 'POP SHOW', subtitle: 'Os maiores sucessos do pop nacional e internacional.' },
    { start: '13:00', end: '13:10', name: 'MÚSICA DO DIA', subtitle: 'O hit que não sai da sua cabeça, em destaque.' },
    { start: '13:10', end: '16:50', name: 'MARATONA520', subtitle: 'Uma sequência de hits sem parar para animar a sua tarde.' },
    { start: '16:50', end: '17:00', name: 'RESENHA520', subtitle: 'O resumo esportivo que você precisa ouvir.' },
    { start: '17:00', end: '18:00', name: 'BR520', subtitle: 'Só o melhor da música brasileira toca aqui.' },
    { start: '18:00', end: '18:05', name: 'HORA DA AVE MARIA', subtitle: 'Um momento de fé e reflexão.' },
    { start: '18:05', end: '20:00', name: 'MIX520 - AS MAIS TOCADAS PELO MUNDO', subtitle: 'A parada de sucessos global da sua rádio.' },
    { start: '20:00', end: '20:10', name: 'REPÓRTER520', subtitle: 'As notícias que movimentam o seu dia.' },
    { start: '20:10', end: '22:00', name: 'RADIO520 - LIVE CONCERT', subtitle: 'A emoção dos grandes shows, ao vivo no seu rádio.' },
    { start: '22:00', end: '22:10', name: 'RÁDIO520 VIVA MELHOR', subtitle: 'Dicas de saúde e bem-estar para uma vida mais leve.' },
    { start: '22:10', end: '24:00', name: 'CLASSIC HITS', subtitle: 'As músicas que marcaram época e continuam inesquecíveis.' },
];

const scheduleTuesday: Program[] = [
    { start: '00:00', end: '00:10', name: 'REPÓRTER520', subtitle: 'As notícias que movimentam o seu dia.' },
    { start: '00:10', end: '02:00', name: 'LOVE HITS', subtitle: 'As melhores canções de amor, de todos os tempos.' },
    { start: '02:00', end: '05:50', name: 'INSÔNIA', subtitle: 'A trilha sonora perfeita para a sua madrugada.' },
    { start: '05:50', end: '06:00', name: 'RÁDIO520 VIVA MELHOR', subtitle: 'Dicas de saúde e bem-estar para uma vida mais leve.' },
    { start: '06:00', end: '07:50', name: 'GIRO520', subtitle: 'Comece o dia bem informado e com muita música.' },
    { start: '07:50', end: '08:00', name: 'MÚSICA DO DIA', subtitle: 'O hit que não sai da sua cabeça, em destaque.' },
    { start: '08:00', end: '10:00', name: 'CAFEÍNA', subtitle: 'A dose extra de energia e música para as suas manhãs.' },
    { start: '10:00', end: '10:10', name: 'REPÓRTER520', subtitle: 'As notícias que movimentam o seu dia.' },
    { start: '10:10', end: '13:00', name: 'POP SHOW', subtitle: 'Os maiores sucessos do pop nacional e internacional.' },
    { start: '13:00', end: '13:10', name: 'MÚSICA DO DIA', subtitle: 'O hit que não sai da sua cabeça, em destaque.' },
    { start: '13:10', end: '16:50', name: 'MARATONA520', subtitle: 'Uma sequência de hits sem parar para animar a sua tarde.' },
    { start: '16:50', end: '17:00', name: 'RESENHA520', subtitle: 'O resumo esportivo que você precisa ouvir.' },
    { start: '17:00', end: '18:00', name: 'BR520', subtitle: 'Só o melhor da música brasileira toca aqui.' },
    { start: '18:00', end: '18:05', name: 'HORA DA AVE MARIA', subtitle: 'Um momento de fé e reflexão.' },
    { start: '18:05', end: '20:00', name: 'MIX520 - AS MAIS TOCADAS PELO MUNDO', subtitle: 'A parada de sucessos global da sua rádio.' },
    { start: '20:00', end: '20:10', name: 'REPÓRTER520', subtitle: 'As notícias que movimentam o seu dia.' },
    { start: '20:10', end: '22:00', name: 'BUSINESS ROCK', subtitle: "Empreendedorismo e rock'n'roll na mesma sintonia." },
    { start: '22:00', end: '22:10', name: 'RÁDIO520 VIVA MELHOR', subtitle: 'Dicas de saúde e bem-estar para uma vida mais leve.' },
    { start: '22:10', end: '24:00', name: 'CLASSIC HITS', subtitle: 'As músicas que marcaram época e continuam inesquecíveis.' },
];

const scheduleWednesday: Program[] = [
    { start: '00:00', end: '00:10', name: 'REPÓRTER520', subtitle: 'As notícias que movimentam o seu dia.' },
    { start: '00:10', end: '02:00', name: 'LOVE HITS', subtitle: 'As melhores canções de amor, de todos os tempos.' },
    { start: '02:00', end: '05:50', name: 'INSÔNIA', subtitle: 'A trilha sonora perfeita para a sua madrugada.' },
    { start: '05:50', end: '06:00', name: 'RÁDIO520 VIVA MELHOR', subtitle: 'Dicas de saúde e bem-estar para uma vida mais leve.' },
    { start: '06:00', end: '07:50', name: 'GIRO520', subtitle: 'Comece o dia bem informado e com muita música.' },
    { start: '07:50', end: '08:00', name: 'MÚSICA DO DIA', subtitle: 'O hit que não sai da sua cabeça, em destaque.' },
    { start: '08:00', end: '10:00', name: 'CAFEÍNA', subtitle: 'A dose extra de energia e música para as suas manhãs.' },
    { start: '10:00', end: '10:10', name: 'REPÓRTER520', subtitle: 'As notícias que movimentam o seu dia.' },
    { start: '10:10', end: '13:00', name: 'POP SHOW', subtitle: 'Os maiores sucessos do pop nacional e internacional.' },
    { start: '13:00', end: '13:10', name: 'MÚSICA DO DIA', subtitle: 'O hit que não sai da sua cabeça, em destaque.' },
    { start: '13:10', end: '16:50', name: 'MARATONA520', subtitle: 'Uma sequência de hits sem parar para animar a sua tarde.' },
    { start: '16:50', end: '17:00', name: 'RESENHA520', subtitle: 'O resumo esportivo que você precisa ouvir.' },
    { start: '17:00', end: '18:00', name: 'BR520', subtitle: 'Só o melhor da música brasileira toca aqui.' },
    { start: '18:00', end: '18:05', name: 'HORA DA AVE MARIA', subtitle: 'Um momento de fé e reflexão.' },
    { start: '18:05', end: '20:00', name: 'MIX520 - AS MAIS TOCADAS PELO MUNDO', subtitle: 'A parada de sucessos global da sua rádio.' },
    { start: '20:00', end: '20:10', name: 'REPÓRTER520', subtitle: 'As notícias que movimentam o seu dia.' },
    { start: '20:10', end: '22:00', name: 'BEATS520', subtitle: 'As batidas que agitam as pistas do mundo todo.' },
    { start: '22:00', end: '22:10', name: 'RÁDIO520 VIVA MELhor', subtitle: 'Dicas de saúde e bem-estar para uma vida mais leve.' },
    { start: '22:10', end: '24:00', name: 'CLASSIC HITS', subtitle: 'As músicas que marcaram época e continuam inesquecíveis.' },
];

const scheduleThursday: Program[] = [
    { start: '00:00', end: '00:10', name: 'REPÓRTER520', subtitle: 'As notícias que movimentam o seu dia.' },
    { start: '00:10', end: '02:00', name: 'LOVE HITS', subtitle: 'As melhores canções de amor, de todos os tempos.' },
    { start: '02:00', end: '05:50', name: 'INSÔNIA', subtitle: 'A trilha sonora perfeita para a sua madrugada.' },
    { start: '05:50', end: '06:00', name: 'RÁDIO520 VIVA MELHOR', subtitle: 'Dicas de saúde e bem-estar para uma vida mais leve.' },
    { start: '06:00', end: '07:50', name: 'GIRO520', subtitle: 'Comece o dia bem informado e com muita música.' },
    { start: '07:50', end: '08:00', name: 'MÚSICA DO DIA', subtitle: 'O hit que não sai da sua cabeça, em destaque.' },
    { start: '08:00', end: '10:00', name: 'CAFEÍNA', subtitle: 'A dose extra de energia e música para as suas manhãs.' },
    { start: '10:00', end: '10:10', name: 'REPÓRTER520', subtitle: 'As notícias que movimentam o seu dia.' },
    { start: '10:10', end: '13:00', name: 'POP SHOW', subtitle: 'Os maiores sucessos do pop nacional e internacional.' },
    { start: '13:00', end: '13:10', name: 'MÚSICA DO DIA', subtitle: 'O hit que não sai da sua cabeça, em destaque.' },
    { start: '13:10', end: '16:50', name: 'MARATONA520', subtitle: 'Uma sequência de hits sem parar para animar a sua tarde.' },
    { start: '16:50', end: '17:00', name: 'RESENHA520', subtitle: 'O resumo esportivo que você precisa ouvir.' },
    { start: '17:00', end: '18:00', name: 'BR520', subtitle: 'Só o melhor da música brasileira toca aqui.' },
    { start: '18:00', end: '18:05', name: 'HORA DA AVE MARIA', subtitle: 'Um momento de fé e reflexão.' },
    { start: '18:05', end: '20:00', name: 'MIX520 - AS MAIS TOCADAS PELO MUNDO', subtitle: 'A parada de sucessos global da sua rádio.' },
    { start: '20:00', end: '20:10', name: 'REPÓRTER520', subtitle: 'As notícias que movimentam o seu dia.' },
    { start: '20:10', end: '22:00', name: 'RÁDIO520 - TOP20', subtitle: 'As 20 músicas mais pedidas da semana.' },
    { start: '22:00', end: '22:10', name: 'RÁDIO520 VIVA MELHOR', subtitle: 'Dicas de saúde e bem-estar para uma vida mais leve.' },
    { start: '22:10', end: '24:00', name: 'CLASSIC HITS', subtitle: 'As músicas que marcaram época e continuam inesquecíveis.' },
];

const scheduleFriday: Program[] = [
    { start: '00:00', end: '00:10', name: 'REPÓRTER520', subtitle: 'As notícias que movimentam o seu dia.' },
    { start: '00:10', end: '02:00', name: 'LOVE HITS', subtitle: 'As melhores canções de amor, de todos os tempos.' },
    { start: '02:00', end: '05:45', name: 'INSÔNIA', subtitle: 'A trilha sonora perfeita para a sua madrugada.' },
    { start: '05:45', end: '06:00', name: 'CARNA520', subtitle: 'O esquenta oficial para o seu fim de semana.' },
    { start: '06:00', end: '07:50', name: 'GIRO520', subtitle: 'Comece o dia bem informado e com muita música.' },
    { start: '07:50', end: '08:00', name: 'MÚSICA DO DIA', subtitle: 'O hit que não sai da sua cabeça, em destaque.' },
    { start: '08:00', end: '10:00', name: 'CAFEÍNA', subtitle: 'A dose extra de energia e música para as suas manhãs.' },
    { start: '10:00', end: '10:10', name: 'MÚSICA DO DIA', subtitle: 'O hit que não sai da sua cabeça, em destaque.' },
    { start: '10:10', end: '13:00', name: 'POP SHOW', subtitle: 'Os maiores sucessos do pop nacional e internacional.' },
    { start: '13:00', end: '13:10', name: 'RÁDIO520 VIVA MELHOR', subtitle: 'Dicas de saúde e bem-estar para uma vida mais leve.' },
    { start: '13:10', end: '16:50', name: 'MARATONA520', subtitle: 'Uma sequência de hits sem parar para animar a sua tarde.' },
    { start: '16:50', end: '17:00', name: 'RESENHA520', subtitle: 'O resumo esportivo que você precisa ouvir.' },
    { start: '17:00', end: '18:00', name: 'BR520', subtitle: 'Só o melhor da música brasileira toca aqui.' },
    { start: '18:00', end: '18:05', name: 'HORA DA AVE MARIA', subtitle: 'Um momento de fé e reflexão.' },
    { start: '18:05', end: '20:00', name: 'MIX520 - AS MAIS TOCADAS PELO MUNDO', subtitle: 'A parada de sucessos global da sua rádio.' },
    { start: '20:00', end: '20:10', name: 'REPÓRTER520', subtitle: 'As notícias que movimentam o seu dia.' },
    { start: '20:10', end: '22:00', name: 'A ERA DO ROCK', subtitle: 'Uma viagem pelos clássicos e novidades do rock.' },
    { start: '22:00', end: '22:10', name: 'RÁDIO520 VIVA MELHOR', subtitle: 'Dicas de saúde e bem-estar para uma vida mais leve.' },
    { start: '22:10', end: '24:00', name: 'CLASSIC HITS', subtitle: 'As músicas que marcaram época e continuam inesquecíveis.' },
];

const scheduleSaturday: Program[] = [
    { start: '00:00', end: '00:10', name: 'REPÓRTER520', subtitle: 'As notícias que movimentam o seu dia.' },
    { start: '00:10', end: '02:00', name: 'LOVE HITS', subtitle: 'As melhores canções de amor, de todos os tempos.' },
    { start: '02:00', end: '10:10', name: 'SUPERSEQUÊNCIA', subtitle: 'Música sem parar, do jeito que você gosta.' },
    { start: '10:10', end: '10:20', name: 'REPÓRTER520', subtitle: 'As notícias que movimentam o seu dia.' },
    { start: '10:20', end: '11:50', name: 'RÁDIO520 - TOP20', subtitle: 'As 20 músicas mais pedidas da semana.' },
    { start: '11:50', end: '12:00', name: 'RÁDIO520 VIVA MELHOR', subtitle: 'Dicas de saúde e bem-estar para uma vida mais leve.' },
    { start: '12:00', end: '14:05', name: 'ZIRIGUIDUM', subtitle: 'O melhor do samba e pagode pra você.' },
    { start: '14:05', end: '14:15', name: 'MÚSICA DO DIA', subtitle: 'O hit que não sai da sua cabeça, em destaque.' },
    { start: '14:15', end: '18:00', name: 'MARATONA520', subtitle: 'Uma sequência de hits sem parar para animar a sua tarde.' },
    { start: '18:00', end: '18:05', name: 'HORA DA AVE MARIA', subtitle: 'Um momento de fé e reflexão.' },
    { start: '18:05', end: '19:50', name: 'BR520', subtitle: 'Só o melhor da música brasileira toca aqui.' },
    { start: '19:50', end: '20:00', name: 'RÁDIO520 VIVA MELHOR', subtitle: 'Dicas de saúde e bem-estar para uma vida mais leve.' },
    { start: '20:00', end: '22:00', name: 'RÁDIO520 - TOP20', subtitle: 'As 20 músicas mais pedidas da semana.' },
    { start: '22:00', end: '24:00', name: 'SUPERSEQUÊNCIA', subtitle: 'Música sem parar, do jeito que você gosta.' },
];

const scheduleSunday: Program[] = [
    { start: '00:00', end: '02:00', name: 'LOVE HITS', subtitle: 'As melhores canções de amor, de todos os tempos.' },
    { start: '02:00', end: '05:00', name: 'SUPERSEQUÊNCIA', subtitle: 'Música sem parar, do jeito que você gosta.' },
    { start: '05:00', end: '07:00', name: 'ORASOM 520', subtitle: 'Músicas para inspirar e renovar a sua fé.' },
    { start: '07:00', end: '11:50', name: 'SUPERSEQUÊNCIA', subtitle: 'Música sem parar, do jeito que você gosta.' },
    { start: '11:50', end: '12:00', name: 'REPÓRTER520', subtitle: 'As notícias que movimentam o seu dia.' },
    { start: '12:00', end: '14:00', name: 'ZIRIGUIDUM', subtitle: 'O melhor do samba e pagode pra você.' },
    { start: '14:00', end: '14:10', name: 'REPÓRTER520', subtitle: 'As notícias que movimentam o seu dia.' },
    { start: '14:10', end: '18:00', name: 'BR520', subtitle: 'Só o melhor da música brasileira toca aqui.' },
    { start: '18:00', end: '18:10', name: 'HORA DA AVE MARIA', subtitle: 'Um momento de fé e reflexão.' },
    { start: '18:10', end: '20:00', name: 'A ERA DO ROCK', subtitle: 'Uma viagem pelos clássicos e novidades do rock.' },
    { start: '20:00', end: '22:00', name: 'ZONA MISTA', subtitle: 'A resenha mais legal e ordinária do rádio mundial.' },
    { start: '22:00', end: '24:00', name: 'TOP BILLBOARD', subtitle: 'Os maiores sucessos das paradas da Billboard.' },
];

export const dailySchedules: Record<number, Program[]> = {
    0: scheduleSunday,
    1: scheduleMonday,
    2: scheduleTuesday,
    3: scheduleWednesday,
    4: scheduleThursday,
    5: scheduleFriday,
    6: scheduleSaturday,
};