export interface Program {
    start: string;
    end: string;
    name: string;
    subtitle?: string;
}

const scheduleSunday: Program[] = [
    { start: '00:00', end: '02:00', name: '520 LOVE HITS', subtitle: 'As melhores baladas românticas.' },
    { start: '02:00', end: '05:00', name: 'SUPERSEQUÊNCIA • DOMINGO', subtitle: 'Músicas sem parar para o seu domingo.' },
    { start: '05:00', end: '07:00', name: 'ORASOM 520', subtitle: 'Momentos de fé e reflexão.' },
    { start: '07:00', end: '11:50', name: 'SUPERSEQUÊNCIA • DOMINGO', subtitle: 'A trilha sonora perfeita para a sua manhã.' },
    { start: '11:50', end: '12:00', name: 'REP520 • DOM', subtitle: 'As notícias que você precisa saber.' },
    { start: '12:00', end: '14:00', name: 'ZIRIGUIDUM', subtitle: 'O melhor do samba e pagode.' },
    { start: '14:00', end: '14:10', name: 'REP520 • DOM', subtitle: 'As notícias que você precisa saber.' },
    { start: '14:10', end: '18:00', name: 'BR520', subtitle: 'Os maiores sucessos da música brasileira.' },
    { start: '18:00', end: '18:10', name: 'HORA DA AVE MARIA - DOMINGO', subtitle: 'Um momento de paz e oração.' },
    { start: '18:10', end: '20:00', name: 'A ERA DO ROCK #05', subtitle: 'Clássicos e novidades do rock.' },
    { start: '20:00', end: '22:00', name: 'ZONA MISTA', subtitle: 'A resenha mais legal e ordinária do rádio.' },
    { start: '22:00', end: '22:10', name: 'REP520 • DOM', subtitle: 'As notícias que você precisa saber.' },
    { start: '22:10', end: '24:00', name: 'TOP BILLBOARD', subtitle: 'Os hits que agitam as paradas mundiais.' },
];

const scheduleMonday: Program[] = [
    { start: '00:00', end: '00:10', name: 'MÚSICA DO DIA 520 • SEG', subtitle: 'O hit que vai marcar o seu dia.' },
    { start: '00:10', end: '02:00', name: '520 LOVE HITS', subtitle: 'As melhores baladas românticas.' },
    { start: '02:00', end: '05:50', name: 'INSÔNIA', subtitle: 'A playlist encerra às 05:42' },
    { start: '05:50', end: '06:00', name: 'REP520 • SEG', subtitle: 'As notícias que você precisa saber.' },
    { start: '06:00', end: '07:50', name: 'GIRO520 • SEG', subtitle: 'As primeiras notícias e músicas do dia.' },
    { start: '07:50', end: '08:00', name: 'MÚSICA DO DIA 520 • SEG', subtitle: 'O hit que vai marcar o seu dia.' },
    { start: '08:00', end: '10:00', name: 'CAFEINA', subtitle: 'Sua dose diária de energia e hits.' },
    { start: '10:00', end: '10:10', name: 'REP520 • SEG', subtitle: 'As notícias que você precisa saber.' },
    { start: '10:10', end: '13:10', name: 'POP SHOW', subtitle: 'Os sucessos que agitam o mundo pop.' },
    { start: '13:10', end: '13:20', name: 'MÚSICA DO DIA 520 • SEG', subtitle: 'O hit que vai marcar o seu dia.' },
    { start: '13:20', end: '16:50', name: 'MARATONA • SEG', subtitle: 'Uma sequência de hits para a sua tarde.' },
    { start: '16:50', end: '17:00', name: 'RESENHA 520', subtitle: 'O resumo do dia com bom humor.' },
    { start: '17:00', end: '18:00', name: 'BR520', subtitle: 'Os maiores sucessos da música brasileira.' },
    { start: '18:00', end: '18:10', name: 'HORA DA AVE MARIA - SEGUNDA', subtitle: 'Um momento de paz e oração.' },
    { start: '18:10', end: '20:00', name: 'MIX520 GEN', subtitle: 'Todos os ritmos em uma só sintonia.' },
    { start: '20:00', end: '20:10', name: 'REP520 • SEG', subtitle: 'As notícias que você precisa saber.' },
    { start: '20:10', end: '22:00', name: 'RÁDIO520 - LIVE CONCERT', subtitle: 'A emoção dos maiores shows no seu rádio.' },
    { start: '22:00', end: '22:10', name: 'MÚSICA DO DIA 520 • SEG', subtitle: 'O hit que vai marcar o seu dia.' },
    { start: '22:10', end: '24:00', name: 'RADIO520 CLASSIC HITS', subtitle: 'As músicas que marcaram época.' },
];

const scheduleTuesday: Program[] = [
    { start: '00:00', end: '00:10', name: 'MUSICA DO DIA • TER', subtitle: 'O hit que vai marcar o seu dia.' },
    { start: '00:10', end: '02:00', name: '520 LOVE HITS', subtitle: 'As melhores baladas românticas.' },
    { start: '02:00', end: '05:50', name: 'INSÔNIA', subtitle: 'A playlist encerra às 05:42' },
    { start: '05:50', end: '06:00', name: 'REP520 • TER', subtitle: 'As notícias que você precisa saber.' },
    { start: '06:00', end: '07:50', name: 'GIRO520 • TER', subtitle: 'As primeiras notícias e músicas do dia.' },
    { start: '07:50', end: '08:00', name: 'MUSICA DO DIA • TER', subtitle: 'O hit que vai marcar o seu dia.' },
    { start: '08:00', end: '10:00', name: 'CAFEINA', subtitle: 'Sua dose diária de energia e hits.' },
    { start: '10:00', end: '10:10', name: 'REP520 • TER', subtitle: 'As notícias que você precisa saber.' },
    { start: '10:10', end: '13:00', name: 'POP SHOW', subtitle: 'Os sucessos que agitam o mundo pop.' },
    { start: '13:00', end: '13:10', name: 'MUSICA DO DIA • TER', subtitle: 'O hit que vai marcar o seu dia.' },
    { start: '13:10', end: '16:50', name: 'MARATONA 520 • TERÇA', subtitle: 'Uma sequência de hits para a sua tarde.' },
    { start: '16:50', end: '17:00', name: 'RESENHA 520', subtitle: 'O resumo do dia com bom humor.' },
    { start: '17:00', end: '18:00', name: 'BR520', subtitle: 'Os maiores sucessos da música brasileira.' },
    { start: '18:00', end: '18:10', name: 'HORA DA AVE MARIA - TERÇA-FEIRA', subtitle: 'Um momento de paz e oração.' },
    { start: '18:10', end: '20:00', name: 'MIX520 GEN', subtitle: 'Todos os ritmos em uma só sintonia.' },
    { start: '20:00', end: '20:10', name: 'REP520 • TER', subtitle: 'As notícias que você precisa saber.' },
    { start: '20:10', end: '22:00', name: 'BUSINESS ROCK', subtitle: 'Rock\'n\'roll para inspirar seus negócios.' },
    { start: '22:00', end: '22:10', name: 'MUSICA DO DIA • TER', subtitle: 'O hit que vai marcar o seu dia.' },
    { start: '22:10', end: '24:00', name: 'RADIO520 CLASSIC HITS', subtitle: 'As músicas que marcaram época.' },
];

const scheduleWednesday: Program[] = [
    { start: '00:00', end: '00:10', name: 'MÚSICA DO DIA • QUA', subtitle: 'A playlist encerra às 00:07' },
    { start: '00:10', end: '02:00', name: '520 LOVE HITS', subtitle: 'As melhores baladas românticas.' },
    { start: '02:00', end: '05:50', name: 'INSÔNIA', subtitle: 'A playlist encerra às 05:42' },
    { start: '05:50', end: '06:00', name: 'REP520 • QUA', subtitle: 'As notícias que você precisa saber.' },
    { start: '06:00', end: '07:50', name: 'GIRO 520 • QUA', subtitle: 'As primeiras notícias e músicas do dia.' },
    { start: '07:50', end: '08:00', name: 'MÚSICA DO DIA • QUA', subtitle: 'O hit que vai marcar o seu dia.' },
    { start: '08:00', end: '10:00', name: 'CAFEINA', subtitle: 'Sua dose diária de energia e hits.' },
    { start: '10:00', end: '10:10', name: 'REP520 • QUA', subtitle: 'As notícias que você precisa saber.' },
    { start: '10:10', end: '13:10', name: 'POP SHOW', subtitle: 'Os sucessos que agitam o mundo pop.' },
    { start: '13:10', end: '13:20', name: 'MÚSICA DO DIA • QUA', subtitle: 'O hit que vai marcar o seu dia.' },
    { start: '13:20', end: '16:50', name: 'MARATONA QUARTA', subtitle: 'Uma sequência de hits para a sua tarde.' },
    { start: '16:50', end: '17:00', name: 'RESENHA 520', subtitle: 'O resumo do dia com bom humor.' },
    { start: '17:00', end: '18:00', name: 'BR520', subtitle: 'Os maiores sucessos da música brasileira.' },
    { start: '18:00', end: '18:10', name: 'HORA DA AVE MARIA - QUARTA-FEIRA', subtitle: 'Um momento de paz e oração.' },
    { start: '18:10', end: '20:00', name: 'MIX520 COM GUI MYNSSEN', subtitle: 'O set mixado que agita sua noite.' },
    { start: '20:00', end: '20:10', name: 'REP520 • QUA', subtitle: 'As notícias que você precisa saber.' },
    { start: '20:10', end: '22:00', name: 'BEATS520', subtitle: 'As batidas da música eletrônica.' },
    { start: '22:00', end: '22:10', name: 'MÚSICA DO DIA • QUA', subtitle: 'O hit que vai marcar o seu dia.' },
    { start: '22:10', end: '24:00', name: 'RADIO520 CLASSIC HITS', subtitle: 'As músicas que marcaram época.' },
];

const scheduleThursday: Program[] = [
    { start: '00:00', end: '00:10', name: 'MÚSICA DO DIA • QUI', subtitle: 'O hit que vai marcar o seu dia.' },
    { start: '00:10', end: '02:00', name: '520 LOVE HITS', subtitle: 'As melhores baladas românticas.' },
    { start: '02:00', end: '05:50', name: 'INSÔNIA', subtitle: 'A playlist encerra às 05:42' },
    { start: '05:50', end: '06:00', name: 'REP520 • QUI', subtitle: 'As notícias que você precisa saber.' },
    { start: '06:00', end: '07:50', name: 'GIRO520 • QUI', subtitle: 'As primeiras notícias e músicas do dia.' },
    { start: '07:50', end: '08:00', name: 'MÚSICA DO DIA • QUI', subtitle: 'O hit que vai marcar o seu dia.' },
    { start: '08:00', end: '10:00', name: 'CAFEINA', subtitle: 'Sua dose diária de energia e hits.' },
    { start: '10:00', end: '10:10', name: 'REP520 • QUI', subtitle: 'As notícias que você precisa saber.' },
    { start: '10:10', end: '13:10', name: 'POP SHOW', subtitle: 'Os sucessos que agitam o mundo pop.' },
    { start: '13:10', end: '13:20', name: 'MÚSICA DO DIA • QUI', subtitle: 'O hit que vai marcar o seu dia.' },
    { start: '13:20', end: '16:50', name: 'MARATONA QUINTA', subtitle: 'Uma sequência de hits para a sua tarde.' },
    { start: '16:50', end: '17:00', name: 'RESENHA 520', subtitle: 'O resumo do dia com bom humor.' },
    { start: '17:00', end: '18:00', name: 'BR520', subtitle: 'Os maiores sucessos da música brasileira.' },
    { start: '18:00', end: '18:10', name: 'HORA DA AVE MARIA', subtitle: 'Um momento de paz e oração.' },
    { start: '18:10', end: '20:00', name: 'MIX520 COM GUI MYNSSEN', subtitle: 'O set mixado que agita sua noite.' },
    { start: '20:00', end: '20:10', name: 'REP520 • QUI', subtitle: 'As notícias que você precisa saber.' },
    { start: '20:10', end: '21:50', name: 'RÁDIO520 TOP20 #SEM16', subtitle: 'A playlist encerra às 21:42' },
    { start: '21:50', end: '22:00', name: 'RADIO520 CLASSIC HITS', subtitle: 'Os clássicos que você não esquece.' },
    { start: '22:00', end: '22:10', name: 'MÚSICA DO DIA • QUI', subtitle: 'O hit que vai marcar o seu dia.' },
    { start: '22:10', end: '24:00', name: 'RADIO520 CLASSIC HITS', subtitle: 'As músicas que marcaram época.' },
];

const scheduleFriday: Program[] = [
    { start: '00:00', end: '00:10', name: 'MÚSICA DO DIA • SEX', subtitle: 'O hit que vai marcar o seu dia.' },
    { start: '00:10', end: '02:00', name: '520 LOVE HITS', subtitle: 'As melhores baladas românticas.' },
    { start: '02:00', end: '05:50', name: 'INSÔNIA', subtitle: 'A playlist encerra às 05:42' },
    { start: '05:50', end: '06:00', name: 'REP 520 • SEX', subtitle: 'As notícias que você precisa saber.' },
    { start: '06:00', end: '07:50', name: 'GIRO520 • SEX', subtitle: 'As primeiras notícias e músicas do dia.' },
    { start: '07:50', end: '08:00', name: 'MÚSICA DO DIA • SEX', subtitle: 'O hit que vai marcar o seu dia.' },
    { start: '08:00', end: '10:00', name: 'CAFEINA', subtitle: 'Sua dose diária de energia e hits.' },
    { start: '10:00', end: '10:10', name: 'REP 520 • SEX', subtitle: 'As notícias que você precisa saber.' },
    { start: '10:10', end: '13:10', name: 'POP SHOW', subtitle: 'Os sucessos que agitam o mundo pop.' },
    { start: '13:10', end: '13:20', name: 'MÚSICA DO DIA • SEX', subtitle: 'O hit que vai marcar o seu dia.' },
    { start: '13:20', end: '16:50', name: 'MARATONA • SEXTA', subtitle: 'Uma sequência de hits para a sua tarde.' },
    { start: '16:50', end: '17:00', name: 'RESENHA 520', subtitle: 'O resumo do dia com bom humor.' },
    { start: '17:00', end: '18:00', name: 'BR520', subtitle: 'Os maiores sucessos da música brasileira.' },
    { start: '18:00', end: '18:10', name: 'HORA DA AVE MARIA - SEXTA', subtitle: 'Um momento de paz e oração.' },
    { start: '18:10', end: '20:00', name: 'MIX520 COM GUI MYNSSEN', subtitle: 'O set mixado que agita sua noite.' },
    { start: '20:00', end: '20:10', name: 'REPÓRTER 520', subtitle: 'As notícias que você precisa saber.' },
    { start: '20:10', end: '22:00', name: 'A ERA DO ROCK #05', subtitle: 'Clássicos e novidades do rock.' },
    { start: '22:00', end: '22:10', name: 'MÚSICA DO DIA • SEX', subtitle: 'O hit que vai marcar o seu dia.' },
    { start: '22:10', end: '24:00', name: 'RADIO520 CLASSIC HITS', subtitle: 'As músicas que marcaram época.' },
];

const scheduleSaturday: Program[] = [
    { start: '00:00', end: '00:10', name: 'MÚSICA DO DIA • SAB', subtitle: 'O hit que vai marcar o seu dia.' },
    { start: '00:10', end: '02:00', name: '520 LOVE HITS', subtitle: 'As melhores baladas românticas.' },
    { start: '02:00', end: '10:10', name: 'SUPERSEQUENCIA • SÁBADO', subtitle: 'Músicas sem parar para o seu sábado.' },
    { start: '10:10', end: '10:20', name: 'REP520 • SAB', subtitle: 'As notícias que você precisa saber.' },
    { start: '10:20', end: '11:50', name: 'RÁDIO520 TOP20 #SEM16', subtitle: 'As 20 músicas mais pedidas da semana.' },
    { start: '11:50', end: '12:00', name: 'VIVA MELHOR com LU SKYLARK', subtitle: 'Dicas para uma vida mais saudável.' },
    { start: '12:00', end: '14:00', name: 'ZIRIGUIDUM', subtitle: 'O melhor do samba e pagode.' },
    { start: '14:00', end: '14:10', name: 'MÚSICA DO DIA • SAB', subtitle: 'O hit que vai marcar o seu dia.' },
    { start: '14:10', end: '18:00', name: 'MARATONA SAB', subtitle: 'Uma sequência de hits para o seu sábado.' },
    { start: '18:00', end: '18:10', name: 'HORA DA AVE MARIA - SÁBADO', subtitle: 'Um momento de paz e oração.' },
    { start: '18:10', end: '19:50', name: 'BR520', subtitle: 'Os maiores sucessos da música brasileira.' },
    { start: '19:50', end: '20:00', name: 'MÚSICA DO DIA • SAB', subtitle: 'O hit que vai marcar o seu dia.' },
    { start: '20:00', end: '22:00', name: 'RADIO520 DANCE CLUB', subtitle: 'O som que agita as pistas de dança.' },
    { start: '22:00', end: '24:00', name: 'RADIO520, A SUA RÁDIO', subtitle: 'A melhor programação, feita pra você.' },
];


export const dailySchedules: Record<number, Program[]> = {
    0: scheduleSunday,
    1: scheduleMonday,
    2: scheduleTuesday,
    3: scheduleWednesday,
    4: scheduleThursday,
    5: scheduleFriday,
    6: scheduleSaturday,
};